# Generated by Django 2.2 on 2020-07-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Hello'),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='Hello'),
        ),
    ]
