# Generated by Django 2.2 on 2020-07-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
        ('wall_app', '0002_auto_20200715_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='messages_liked', to='log_reg_app.User'),
        ),
    ]
